name: CI Pipeline

on:
  push:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install env
        uses: ./.github/actions/install-python-env

      - name: Black
        run: |
          source .venv/bin/activate
          black datek_agar_kivy/ --check
